### ISSUE TITLE
SFM3000 not working after reset

### ISSUE THREAD

**Issue by VictorCasadoZ** [Sensirion/sfm3000-stm-sample-project#3]
Dear Sirs, I have been using a SFM3000 for a while, I have the power lines through a MOSFET, in order to reset it when it freezes (more usual than I would wanted...), the problem is that when the system starts, the sensor works, but after a while it freezes, the power is disconected for the sensor, reconnected, reinitialized, but when I send the get value command, it does not respond to the command...

Here I attach two screenshots of my scope (red channel SDA, yellow channel SCL):

Here is the read command propperly working:
![8c284e01-b44a-47d7-b1ad-ed44a0d5667c](https://user-images.githubusercontent.com/18699271/174600105-09540c2b-59bb-4017-84d7-1e5169802645.jpg)

Here is the read command not being answered by the sensor:
![cd8c7073-bd73-4b18-ad32-670d33fbea94](https://user-images.githubusercontent.com/18699271/174600111-bf6c23bf-052f-4248-8d92-19ff55f8a919.jpg)

Thank you so much!

**Comment by psachs** [comment]
Thank you for the report. I will forward your issue to the SFM product team and see if they can help you resolving this issue

**Comment by psachs** [comment]
Hi @VictorCasadoZ 

Can you please have a look at Section 7 of the datasheet: https://sensirion.com/resource/application_note/sfm/I2C_description

> The I2C interface of the SFM3xxxx show deviations from the NXP I2C specification and might lock up and cease
to react (including to the soft reset command), ...

There is a description under which circumstances the SFM3000 sensor might freeze and can only be fixed through a hard reset
